/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio5;

import java.awt.Color;

/**
 *
 * @author USER
 * @param 
 */
public class DatosEstudiante extends javax.swing.JFrame {
ListaEstudiantes padre;
int HayEstudiante = 0;
int index = 0;
    /**
     * Creates new form DatosEstudiante
     */
    public DatosEstudiante() {
        initComponents();
    }
    
    public DatosEstudiante(ListaEstudiantes padre2) {
        this.padre = padre2;
        HayEstudiante = 0;
        initComponents();
    }
    
    public DatosEstudiante(ListaEstudiantes padre2, Estudiante est, int index) {
        this.padre = padre2;
        HayEstudiante = 1;
        this.index = index;
        initComponents();
        
        txt_nombre.setText(est.getNombre());
        txt_apellido.setText(est.getApellido());
        txt_dni.setText(est.getDni());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_guardar = new javax.swing.JLabel();
        lbl_tituloDE = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_cancelar = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        lbl_dni = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_dni = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        lbl_cuadro1 = new javax.swing.JLabel();
        lbl_cuadro2 = new javax.swing.JLabel();
        lbl_cuadro3 = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_guardar.setText("    GUARDAR  ");
        jPanel1.add(lbl_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 80, 30));

        lbl_tituloDE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tituloDE.setText("DATOS ESTUDIANTE");
        jPanel1.add(lbl_tituloDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lbl_nombre.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_nombre.setText("NOMBRE:");
        jPanel1.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 40));

        lbl_cancelar.setText("   CANCELAR  ");
        jPanel1.add(lbl_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, 30));

        lbl_apellido.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_apellido.setText("APELLIDO:");
        jPanel1.add(lbl_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 40));

        lbl_dni.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_dni.setText("DNI:");
        jPanel1.add(lbl_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 40));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecRojoG.png"))); // NOI18N
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseExited(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, -1));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecVerde.png"))); // NOI18N
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_guardarMouseExited(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        txt_nombre.setBorder(null);
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 140, 20));

        txt_dni.setBorder(null);
        jPanel1.add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, 20));

        txt_apellido.setBorder(null);
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 20));

        lbl_cuadro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecBlanco.png"))); // NOI18N
        jPanel1.add(lbl_cuadro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 40));

        lbl_cuadro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecBlanco.png"))); // NOI18N
        jPanel1.add(lbl_cuadro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 40));

        lbl_cuadro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecBlanco.png"))); // NOI18N
        jPanel1.add(lbl_cuadro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 40));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo.png"))); // NOI18N
        jPanel1.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 300, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseEntered
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecRojoO.png")));
        lbl_cancelar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_cancelarMouseEntered

    private void btn_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseExited
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecRojoG.png")));
        lbl_cancelar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_cancelarMouseExited

    private void btn_guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseEntered
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecVerdeO.png")));
        lbl_guardar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_guardarMouseEntered

    private void btn_guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseExited
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecVerde.png")));
        lbl_guardar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_guardarMouseExited

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
       padre.setLocationRelativeTo(this);
       padre.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        Estudiante est = new Estudiante();
        
        est.setNombre(txt_nombre.getText());
        est.setApellido(txt_apellido.getText());
        est.setDni(txt_dni.getText());        
       
        padre.TenerDatosEstudiante(est, HayEstudiante, index);
        
        padre.setLocationRelativeTo(this);
        padre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_guardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cancelar;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_cancelar;
    private javax.swing.JLabel lbl_cuadro1;
    private javax.swing.JLabel lbl_cuadro2;
    private javax.swing.JLabel lbl_cuadro3;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_guardar;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_tituloDE;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
