/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio5;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author USER
 */
public class ListaEstudiantes extends javax.swing.JFrame {
    private DefaultListModel<String> modeloNombres = new DefaultListModel<>();
    private ArrayList<Estudiante> listaEstudiantes2 = new ArrayList<>();

    /**
     * Creates new form ListaEstudiantes
     */
    public ListaEstudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_buscar = new javax.swing.JTextField();
        lbl_editar = new javax.swing.JLabel();
        lbl_agregar = new javax.swing.JLabel();
        lbl_cuadro = new javax.swing.JLabel();
        lbl_eliminar = new javax.swing.JLabel();
        lbl_buscar = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_estudiantes = new javax.swing.JList<>();
        btn_editar = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_buscar.setBorder(null);
        jPanel1.add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 20));

        lbl_editar.setText(" EDITAR");
        jPanel1.add(lbl_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 50, 30));

        lbl_agregar.setText("  AGREGAR  ");
        jPanel1.add(lbl_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 70, 30));

        lbl_cuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecBlanco.png"))); // NOI18N
        jPanel1.add(lbl_cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 40));

        lbl_eliminar.setText("  ELIMINAR  ");
        jPanel1.add(lbl_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 30));

        lbl_buscar.setText("BUSCAR");
        jPanel1.add(lbl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 70, 40));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecBlanco2.png"))); // NOI18N
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, 40));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecRojo.png"))); // NOI18N
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseExited(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecCeleste.png"))); // NOI18N
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregarMouseExited(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        list_estudiantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_estudiantes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86, 230, 170));

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecAzul.png"))); // NOI18N
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editarMouseExited(evt);
            }
        });
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setText("LISTA ESTUDIANTES");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo.png"))); // NOI18N
        jPanel1.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 280, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseEntered
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecCelesteO.png")));
        lbl_agregar.setForeground(Color.white);
        
    }//GEN-LAST:event_btn_agregarMouseEntered

    private void btn_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseExited
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecCeleste.png")));
        lbl_agregar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_agregarMouseExited

    private void btn_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseEntered
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecRojoPO.png")));
        lbl_eliminar.setForeground(Color.white);
    }//GEN-LAST:event_btn_eliminarMouseEntered

    private void btn_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseExited
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecRojo.png")));
        lbl_eliminar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_eliminarMouseExited

    private void btn_editarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseEntered
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecAzulO.png")));
        lbl_editar.setForeground(Color.white);
    }//GEN-LAST:event_btn_editarMouseEntered

    private void btn_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseExited
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecAzul.png")));
        lbl_editar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_editarMouseExited

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        DatosEstudiante ventana2 = new DatosEstudiante(this);
        ventana2.setLocationRelativeTo(this);
        ventana2.setVisible(true);
        this.setVisible(false);       
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseClicked
        int selectedIndex = list_estudiantes.getSelectedIndex();
        Estudiante est = listaEstudiantes2.get(selectedIndex);
        
        DatosEstudiante ventana2 = new DatosEstudiante(this, est,
                selectedIndex);
        ventana2.setLocationRelativeTo(this);
        ventana2.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btn_editarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        int selectedIndex = list_estudiantes.getSelectedIndex();
        
        
        modeloNombres.remove(selectedIndex);
        listaEstudiantes2.remove(selectedIndex);
        list_estudiantes.remove(selectedIndex);
    }//GEN-LAST:event_btn_eliminarMouseClicked
    
    public void TenerDatosEstudiante(Estudiante est, int HayEstudiante, int index)
    {
        if (HayEstudiante == 0)
        {
        String nombre = est.getNombre() + " " + est.getApellido() + " " 
                + est.getDni();
        String nombreString = nombre;
        
        list_estudiantes.setModel(modeloNombres);
        listaEstudiantes2.add(est);
        modeloNombres.addElement(nombreString);
        }
        if (HayEstudiante == 1)
        {
            String nombre = est.getNombre() + " " + est.getApellido() + " " 
                + est.getDni();
            list_estudiantes.setModel(modeloNombres);
            
            listaEstudiantes2.add(index, est);
            listaEstudiantes2.remove(index + 1);
            
            modeloNombres.add(index, nombre);
            modeloNombres.remove(index + 1);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_agregar;
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_editar;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_agregar;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_cuadro;
    private javax.swing.JLabel lbl_editar;
    private javax.swing.JLabel lbl_eliminar;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JList<String> list_estudiantes;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
